language: ruby
rvm:
- 2.5.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  YOUR_API_KEY:
    secure: YOUR_SECURE_KEY
    app:
    develop: YOUR_DEVELOPMENT_APP
    master: YOUR_PRODUCTION_APP
    on:
    repo: GITHUB_UNAME/REPO_NAME
  run:
    - "rails db:migrate"
